### ISSUE TITLE
[Feature] Support for custom ERC20 tokens

### ISSUE THREAD

**Issue by mesqueeb** [Dappos/Dappos#34]
Support for custom ERC20 tokens

### Todo

- [x] Add the required UI
Below the custom RPC settings:
[Example code from custom RPC](https://github.com/Dappos/Dappos/blob/master/src/components/Settings.vue#L49)
![image](https://user-images.githubusercontent.com/3253920/47903097-8e793880-dec6-11e8-81c9-0dde4ae2ecd3.png)

- [x] Modify store to save the ERC20 information in database
[Example code from custom RPC](https://github.com/Dappos/Dappos/blob/master/src/store/modules/settings.js#L20)
[Example data from DAI](https://github.com/Dappos/Dappos/blob/master/src/config/selectableTokens.js)

- [x] Update UI to allow saving the custom ERC20 information
[Example code from custom RPC](https://github.com/Dappos/Dappos/blob/master/src/components/Settings.vue#L118)

- [x] Update payment modal so custom added ERC20 tokens are selectable if on correct network
[Example code DAI](https://github.com/Dappos/Dappos/blob/master/src/components/Modals/Payment.vue#L21)
![image](https://user-images.githubusercontent.com/3253920/47903795-8241ab00-dec7-11e8-8baa-f8ea1b095ed0.png)

- [ ] Update conversion API of coinmarketcap to work with custom ERC20 tokens.

**Comment by 6proof** [comment]
Great job!  Now if we can add an API call to Coin Market Cap or similar, we can set price in ERC20 and show equivalency in USD, JPY, or whatever default is set. Great work!  looking forward to testing when ready.

**Comment by 6proof** [comment]
an excellent use case is to add a custom ERC20 (compatible) token with eventual ability to show paired market price in that token.  This API call for pricing can be added later.  Perhaps we could work with the Trust Wallet Team on this.

For Example, Trust Wallet App has long supported POA Network and the POA Native Coin.  RPC Server is https://core.poa.network , token is POA.  If we set custom RPC to https://core.poa.network and include "POA" as selectable token, all that need be done is make sure POA <custom ERC20> is added in list of currencies with which store can be priced.  After this we can potentially work with the Trust Wallet App API for token prices and encourage Dappos vendors to poing customers to use Trust Wallet App.

**Comment by mesqueeb** [comment]
Closed in #38
